still checking

diff --git a/.github/workflows/ansible.yml b/.github/workflows/ansible.yml
--- a/.github/workflows/ansible.yml
+++ b/.github/workflows/ansible.yml
@@ -39,11 +39,19 @@ jobs:
    - name: Debug SSH key
      run: ls -l ~/.ssh/ec2_key.pem
 
+   - name: Verify MONGO_URI Secret
+     run: |
+      if [[ -n "${{ secrets.MONGO_URI }}" && "${{ secrets.MONGO_URI }}" == "mongodb"* ]]; then
+       echo "✅ MONGO_URI secret is available and starts with 'mongodb'."
+      else
+       echo "❌ CRITICAL: MONGO_URI secret is empty, invalid, or not accessible."
+      exit 1
+      fi
    - name: Run Ansible playbook
      run: |
       ansible-playbook ansible/playbooks/provision_and_configure_server.yml \
-      -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem" 
-#      -e "MONGO_URI={{ secrets.MONGO_URI }}"
+      -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem" \
+      -e 'MONGO_URI=${{ secrets.MONGO_URI }}'
 
      env:
       # AWS_SECRET_ACCESS_KEY: {{ secrets.AWS_SECRET_ACCESS_ID }}
